apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ordermanagementmicroservice
  name: ordermanagementmicroservice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ordermanagementmicroservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ordermanagementmicroservice
    spec:
      containers:
        - image: dulanji15/ordermanagemnetmicroservice:{{tag}}
          imagePullPolicy: Always
          name: ordermanagemnetmicroservice
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30